function FM = drag_calculator_base(A, B, mu, theta, alpha, omega, v, x, y, fai0, vn, type)
% drag_calculator_base   obtain localized force and moment
% Invoking               none
% Invoked                drag_calculator
% INPUT
%   A,B,mu               scalar, Cavity Expansion Model's coefficient
%   theta                scalar, the angle between surface's tangential direction and rotational axis
%   alpha                scalar, the angle of attack
%   omega                scalar, angular velocity
%   v                    scalar, the absolute peneration velocity
%   x                    scalar, element's axial location
%   y                    scalar, element's radius
%   fai0                 scalar, element's radial limit contact angle
%   vn                   scalar, element's nomal velocity
%   type                 scalar, indicator:
%                        1- Part side, mode 1 (-pi - fai, fai)
%                        2- Part side, mode 2 (-fai, pi + fai)
%                        3- All side
% OUTPUT
%   FM                   vector of 4x1, [Flx; Fly; M; Fr]
%%
costheta = cos(theta);
sintheta = sin(theta);
cosalpha = cos(alpha);
sinalpha = sin(alpha);
cosfai0 = cos(fai0);
sinfai0 = sin(fai0);
sin2fai0 = sin(2*fai0);

if vn ~= 0 && omega ~= 0
    switch type
        case 3

            FM = [-y*pi*(sintheta + mu*costheta)*(2*A + 2*B*vn^2 + B*omega^2*x^2*costheta^2 + B*omega^2*y^2*sintheta^2 + 2*B*v^2*cosalpha^2*sintheta^2 + B*v^2*sinalpha^2*costheta^2 + 4*B*v*vn*cosalpha*sintheta - B*omega^2*x*y*sin(2*theta) + 2*B*omega*v*x*sinalpha*costheta^2 - 2*B*omega*v*y*sinalpha*costheta*sintheta);
                 -2*B*y*pi*(vn + v*cosalpha*sintheta)*(costheta - mu*sintheta)*(omega*x*costheta - omega*y*sintheta + v*sinalpha*costheta);
                 2*B*y*pi*(vn + v*cosalpha*sintheta)*(omega*x*costheta - omega*y*sintheta + v*sinalpha*costheta)*(y*sintheta - x*costheta + mu*y*costheta + mu*x*sintheta)
                 -y*pi*(costheta - mu*sintheta)*(2*A + 2*B*vn^2 + B*omega^2*x^2*costheta^2 + B*omega^2*y^2*sintheta^2 + 2*B*v^2*cosalpha^2*sintheta^2 + B*v^2*sinalpha^2*costheta^2 + 4*B*v*vn*cosalpha*sintheta - B*omega^2*x*y*sin(2*theta) + 2*B*omega*v*x*sinalpha*costheta^2 - 2*B*omega*v*y*sinalpha*costheta*sintheta)];       
        case 1

            FM = [-(y*(sintheta + mu*costheta)*(4*A*fai0 + 2*pi*A + 2*pi*B*vn^2 + 4*B*fai0*vn^2 - B*v^2*sin2fai0*sinalpha^2*costheta^2 + 2*pi*B*v^2*cosalpha^2*sintheta^2 + pi*B*v^2*sinalpha^2*costheta^2 + 4*B*fai0*v^2*cosalpha^2*sintheta^2 + 2*B*fai0*v^2*sinalpha^2*costheta^2 - B*omega^2*x^2*sin2fai0*costheta^2 - B*omega^2*y^2*sin2fai0*sintheta^2 + pi*B*omega^2*x^2*costheta^2 + pi*B*omega^2*y^2*sintheta^2 + 2*B*fai0*omega^2*x^2*costheta^2 + 2*B*fai0*omega^2*y^2*sintheta^2 - 8*B*v*vn*cosfai0*sinalpha*costheta - 2*B*fai0*omega^2*x*y*sin(2*theta) + 4*pi*B*v*vn*cosalpha*sintheta + 8*B*fai0*v*vn*cosalpha*sintheta - 8*B*omega*vn*x*cosfai0*costheta + 8*B*omega*vn*y*cosfai0*sintheta - B*omega^2*x*y*pi*sin(2*theta) - 2*B*omega*v*x*sin2fai0*sinalpha*costheta^2 + 2*B*omega^2*x*y*sin2fai0*costheta*sintheta + 2*pi*B*omega*v*x*sinalpha*costheta^2 + 4*B*fai0*omega*v*x*sinalpha*costheta^2 - 8*B*v^2*cosalpha*cosfai0*sinalpha*costheta*sintheta + 8*B*omega*v*y*cosalpha*cosfai0*sintheta^2 - 8*B*omega*v*x*cosalpha*cosfai0*costheta*sintheta + 2*B*omega*v*y*sin2fai0*sinalpha*costheta*sintheta - 2*pi*B*omega*v*y*sinalpha*costheta*sintheta - 4*B*fai0*omega*v*y*sinalpha*costheta*sintheta))/2;
                 (y*(costheta - mu*sintheta)*(6*A*cosfai0 + 6*B*vn^2*cosfai0 - 2*B*v^2*cosfai0^3*sinalpha^2*costheta^2 + 6*B*omega^2*x^2*cosfai0*costheta^2 + 6*B*omega^2*y^2*cosfai0*sintheta^2 - 2*B*omega^2*x^2*cosfai0^3*costheta^2 + 6*B*v^2*cosfai0*sinalpha^2*costheta^2 + 6*B*v^2*cosalpha^2*cosfai0*sintheta^2 - 2*B*omega^2*y^2*cosfai0^3*sintheta^2 + 12*B*v*vn*cosalpha*cosfai0*sintheta + 3*B*omega*vn*x*sin2fai0*costheta - 3*B*omega*vn*y*sin2fai0*sintheta - 3*pi*B*omega*vn*x*costheta + 3*pi*B*omega*vn*y*sintheta - 6*B*fai0*omega*vn*x*costheta + 6*B*fai0*omega*vn*y*sintheta + 3*B*v*vn*sin2fai0*sinalpha*costheta - 3*pi*B*v*vn*sinalpha*costheta - 6*B*fai0*v*vn*sinalpha*costheta + 3*B*v^2*sin2fai0*cosalpha*sinalpha*costheta*sintheta - 3*pi*B*v^2*cosalpha*sinalpha*costheta*sintheta - 4*B*omega*v*x*cosfai0^3*sinalpha*costheta^2 - 6*B*fai0*v^2*cosalpha*sinalpha*costheta*sintheta - 3*B*omega*v*y*sin2fai0*cosalpha*sintheta^2 + 4*B*omega^2*x*y*cosfai0^3*costheta*sintheta + 3*pi*B*omega*v*y*cosalpha*sintheta^2 + 6*B*fai0*omega*v*y*cosalpha*sintheta^2 + 12*B*omega*v*x*cosfai0*sinalpha*costheta^2 - 12*B*omega^2*x*y*cosfai0*costheta*sintheta - 12*B*omega*v*y*cosfai0*sinalpha*costheta*sintheta + 3*B*omega*v*x*sin2fai0*cosalpha*costheta*sintheta + 4*B*omega*v*y*cosfai0^3*sinalpha*costheta*sintheta - 3*pi*B*omega*v*x*cosalpha*costheta*sintheta - 6*B*fai0*omega*v*x*cosalpha*costheta*sintheta))/3;
                 -(y*(y*sintheta - x*costheta + mu*y*costheta + mu*x*sintheta)*(6*A*cosfai0 + 6*B*vn^2*cosfai0 - 2*B*v^2*cosfai0^3*sinalpha^2*costheta^2 + 6*B*omega^2*x^2*cosfai0*costheta^2 + 6*B*omega^2*y^2*cosfai0*sintheta^2 - 2*B*omega^2*x^2*cosfai0^3*costheta^2 + 6*B*v^2*cosfai0*sinalpha^2*costheta^2 + 6*B*v^2*cosalpha^2*cosfai0*sintheta^2 - 2*B*omega^2*y^2*cosfai0^3*sintheta^2 + 12*B*v*vn*cosalpha*cosfai0*sintheta + 3*B*omega*vn*x*sin2fai0*costheta - 3*B*omega*vn*y*sin2fai0*sintheta - 3*pi*B*omega*vn*x*costheta + 3*pi*B*omega*vn*y*sintheta - 6*B*fai0*omega*vn*x*costheta + 6*B*fai0*omega*vn*y*sintheta + 3*B*v*vn*sin2fai0*sinalpha*costheta - 3*pi*B*v*vn*sinalpha*costheta - 6*B*fai0*v*vn*sinalpha*costheta + 3*B*v^2*sin2fai0*cosalpha*sinalpha*costheta*sintheta - 3*pi*B*v^2*cosalpha*sinalpha*costheta*sintheta - 4*B*omega*v*x*cosfai0^3*sinalpha*costheta^2 - 6*B*fai0*v^2*cosalpha*sinalpha*costheta*sintheta - 3*B*omega*v*y*sin2fai0*cosalpha*sintheta^2 + 4*B*omega^2*x*y*cosfai0^3*costheta*sintheta + 3*pi*B*omega*v*y*cosalpha*sintheta^2 + 6*B*fai0*omega*v*y*cosalpha*sintheta^2 + 12*B*omega*v*x*cosfai0*sinalpha*costheta^2 - 12*B*omega^2*x*y*cosfai0*costheta*sintheta - 12*B*omega*v*y*cosfai0*sinalpha*costheta*sintheta + 3*B*omega*v*x*sin2fai0*cosalpha*costheta*sintheta + 4*B*omega*v*y*cosfai0^3*sinalpha*costheta*sintheta - 3*pi*B*omega*v*x*cosalpha*costheta*sintheta - 6*B*fai0*omega*v*x*cosalpha*costheta*sintheta))/3
                 -(y*(costheta - mu*sintheta)*(4*A*fai0 + 2*pi*A + 2*pi*B*vn^2 + 4*B*fai0*vn^2 + 2*pi*B*v^2*cosalpha^2*sintheta^2 + pi*B*v^2*sinalpha^2*costheta^2 + 4*B*fai0*v^2*cosalpha^2*sintheta^2 + 2*B*fai0*v^2*sinalpha^2*costheta^2 + pi*B*omega^2*x^2*costheta^2 + pi*B*omega^2*y^2*sintheta^2 + 2*B*fai0*omega^2*x^2*costheta^2 + 2*B*fai0*omega^2*y^2*sintheta^2 - 8*B*v*vn*cosfai0*sinalpha*costheta - 2*B*fai0*omega^2*x*y*sin(2*theta) - 2*B*omega^2*x^2*cosfai0*costheta^2*sinfai0 - 2*B*omega^2*y^2*cosfai0*sinfai0*sintheta^2 - 2*B*v^2*cosfai0*sinalpha^2*costheta^2*sinfai0 + 4*pi*B*v*vn*cosalpha*sintheta + 8*B*fai0*v*vn*cosalpha*sintheta - 8*B*omega*vn*x*cosfai0*costheta + 8*B*omega*vn*y*cosfai0*sintheta - B*omega^2*x*y*pi*sin(2*theta) + 2*pi*B*omega*v*x*sinalpha*costheta^2 + 4*B*fai0*omega*v*x*sinalpha*costheta^2 - 8*B*v^2*cosalpha*cosfai0*sinalpha*costheta*sintheta + 8*B*omega*v*y*cosalpha*cosfai0*sintheta^2 - 8*B*omega*v*x*cosalpha*cosfai0*costheta*sintheta - 4*B*omega*v*x*cosfai0*sinalpha*costheta^2*sinfai0 + 4*B*omega^2*x*y*cosfai0*costheta*sinfai0*sintheta - 2*pi*B*omega*v*y*sinalpha*costheta*sintheta - 4*B*fai0*omega*v*y*sinalpha*costheta*sintheta + 4*B*omega*v*y*cosfai0*sinalpha*costheta*sinfai0*sintheta))/2];
        case 2

            FM = [-(y*(sintheta + mu*costheta)*(4*A*fai0 + 2*pi*A + 2*pi*B*vn^2 + 4*B*fai0*vn^2 - B*v^2*sin2fai0*sinalpha^2*costheta^2 + 2*pi*B*v^2*cosalpha^2*sintheta^2 + pi*B*v^2*sinalpha^2*costheta^2 + 4*B*fai0*v^2*cosalpha^2*sintheta^2 + 2*B*fai0*v^2*sinalpha^2*costheta^2 - B*omega^2*x^2*sin2fai0*costheta^2 - B*omega^2*y^2*sin2fai0*sintheta^2 + pi*B*omega^2*x^2*costheta^2 + pi*B*omega^2*y^2*sintheta^2 + 2*B*fai0*omega^2*x^2*costheta^2 + 2*B*fai0*omega^2*y^2*sintheta^2 + 8*B*v*vn*cosfai0*sinalpha*costheta - 2*B*fai0*omega^2*x*y*sin(2*theta) + 4*pi*B*v*vn*cosalpha*sintheta + 8*B*fai0*v*vn*cosalpha*sintheta + 8*B*omega*vn*x*cosfai0*costheta - 8*B*omega*vn*y*cosfai0*sintheta - B*omega^2*x*y*pi*sin(2*theta) - 2*B*omega*v*x*sin2fai0*sinalpha*costheta^2 + 2*B*omega^2*x*y*sin2fai0*costheta*sintheta + 2*pi*B*omega*v*x*sinalpha*costheta^2 + 4*B*fai0*omega*v*x*sinalpha*costheta^2 + 8*B*v^2*cosalpha*cosfai0*sinalpha*costheta*sintheta - 8*B*omega*v*y*cosalpha*cosfai0*sintheta^2 + 8*B*omega*v*x*cosalpha*cosfai0*costheta*sintheta + 2*B*omega*v*y*sin2fai0*sinalpha*costheta*sintheta - 2*pi*B*omega*v*y*sinalpha*costheta*sintheta - 4*B*fai0*omega*v*y*sinalpha*costheta*sintheta))/2;
                -(y*(costheta - mu*sintheta)*(6*A*cosfai0 + 6*B*vn^2*cosfai0 - 2*B*v^2*cosfai0^3*sinalpha^2*costheta^2 + 6*B*omega^2*x^2*cosfai0*costheta^2 + 6*B*omega^2*y^2*cosfai0*sintheta^2 - 2*B*omega^2*x^2*cosfai0^3*costheta^2 + 6*B*v^2*cosfai0*sinalpha^2*costheta^2 + 6*B*v^2*cosalpha^2*cosfai0*sintheta^2 - 2*B*omega^2*y^2*cosfai0^3*sintheta^2 + 12*B*v*vn*cosalpha*cosfai0*sintheta - 3*B*omega*vn*x*sin2fai0*costheta + 3*B*omega*vn*y*sin2fai0*sintheta + 3*pi*B*omega*vn*x*costheta - 3*pi*B*omega*vn*y*sintheta + 6*B*fai0*omega*vn*x*costheta - 6*B*fai0*omega*vn*y*sintheta - 3*B*v*vn*sin2fai0*sinalpha*costheta + 3*pi*B*v*vn*sinalpha*costheta + 6*B*fai0*v*vn*sinalpha*costheta - 3*B*v^2*sin2fai0*cosalpha*sinalpha*costheta*sintheta + 3*pi*B*v^2*cosalpha*sinalpha*costheta*sintheta - 4*B*omega*v*x*cosfai0^3*sinalpha*costheta^2 + 6*B*fai0*v^2*cosalpha*sinalpha*costheta*sintheta + 3*B*omega*v*y*sin2fai0*cosalpha*sintheta^2 + 4*B*omega^2*x*y*cosfai0^3*costheta*sintheta - 3*pi*B*omega*v*y*cosalpha*sintheta^2 - 6*B*fai0*omega*v*y*cosalpha*sintheta^2 + 12*B*omega*v*x*cosfai0*sinalpha*costheta^2 - 12*B*omega^2*x*y*cosfai0*costheta*sintheta - 12*B*omega*v*y*cosfai0*sinalpha*costheta*sintheta - 3*B*omega*v*x*sin2fai0*cosalpha*costheta*sintheta + 4*B*omega*v*y*cosfai0^3*sinalpha*costheta*sintheta + 3*pi*B*omega*v*x*cosalpha*costheta*sintheta + 6*B*fai0*omega*v*x*cosalpha*costheta*sintheta))/3;
                (y*(y*sintheta - x*costheta + mu*y*costheta + mu*x*sintheta)*(6*A*cosfai0 + 6*B*vn^2*cosfai0 - 2*B*v^2*cosfai0^3*sinalpha^2*costheta^2 + 6*B*omega^2*x^2*cosfai0*costheta^2 + 6*B*omega^2*y^2*cosfai0*sintheta^2 - 2*B*omega^2*x^2*cosfai0^3*costheta^2 + 6*B*v^2*cosfai0*sinalpha^2*costheta^2 + 6*B*v^2*cosalpha^2*cosfai0*sintheta^2 - 2*B*omega^2*y^2*cosfai0^3*sintheta^2 + 12*B*v*vn*cosalpha*cosfai0*sintheta - 3*B*omega*vn*x*sin2fai0*costheta + 3*B*omega*vn*y*sin2fai0*sintheta + 3*pi*B*omega*vn*x*costheta - 3*pi*B*omega*vn*y*sintheta + 6*B*fai0*omega*vn*x*costheta - 6*B*fai0*omega*vn*y*sintheta - 3*B*v*vn*sin2fai0*sinalpha*costheta + 3*pi*B*v*vn*sinalpha*costheta + 6*B*fai0*v*vn*sinalpha*costheta - 3*B*v^2*sin2fai0*cosalpha*sinalpha*costheta*sintheta + 3*pi*B*v^2*cosalpha*sinalpha*costheta*sintheta - 4*B*omega*v*x*cosfai0^3*sinalpha*costheta^2 + 6*B*fai0*v^2*cosalpha*sinalpha*costheta*sintheta + 3*B*omega*v*y*sin2fai0*cosalpha*sintheta^2 + 4*B*omega^2*x*y*cosfai0^3*costheta*sintheta - 3*pi*B*omega*v*y*cosalpha*sintheta^2 - 6*B*fai0*omega*v*y*cosalpha*sintheta^2 + 12*B*omega*v*x*cosfai0*sinalpha*costheta^2 - 12*B*omega^2*x*y*cosfai0*costheta*sintheta - 12*B*omega*v*y*cosfai0*sinalpha*costheta*sintheta - 3*B*omega*v*x*sin2fai0*cosalpha*costheta*sintheta + 4*B*omega*v*y*cosfai0^3*sinalpha*costheta*sintheta + 3*pi*B*omega*v*x*cosalpha*costheta*sintheta + 6*B*fai0*omega*v*x*cosalpha*costheta*sintheta))/3
                -(y*(costheta - mu*sintheta)*(4*A*fai0 + 2*pi*A + 2*pi*B*vn^2 + 4*B*fai0*vn^2 + 2*pi*B*v^2*cosalpha^2*sintheta^2 + pi*B*v^2*sinalpha^2*costheta^2 + 4*B*fai0*v^2*cosalpha^2*sintheta^2 + 2*B*fai0*v^2*sinalpha^2*costheta^2 + pi*B*omega^2*x^2*costheta^2 + pi*B*omega^2*y^2*sintheta^2 + 2*B*fai0*omega^2*x^2*costheta^2 + 2*B*fai0*omega^2*y^2*sintheta^2 + 8*B*v*vn*cosfai0*sinalpha*costheta - 2*B*fai0*omega^2*x*y*sin(2*theta) - 2*B*omega^2*x^2*cosfai0*costheta^2*sinfai0 - 2*B*omega^2*y^2*cosfai0*sinfai0*sintheta^2 - 2*B*v^2*cosfai0*sinalpha^2*costheta^2*sinfai0 + 4*pi*B*v*vn*cosalpha*sintheta + 8*B*fai0*v*vn*cosalpha*sintheta + 8*B*omega*vn*x*cosfai0*costheta - 8*B*omega*vn*y*cosfai0*sintheta - B*omega^2*x*y*pi*sin(2*theta) + 2*pi*B*omega*v*x*sinalpha*costheta^2 + 4*B*fai0*omega*v*x*sinalpha*costheta^2 + 8*B*v^2*cosalpha*cosfai0*sinalpha*costheta*sintheta - 8*B*omega*v*y*cosalpha*cosfai0*sintheta^2 + 8*B*omega*v*x*cosalpha*cosfai0*costheta*sintheta - 4*B*omega*v*x*cosfai0*sinalpha*costheta^2*sinfai0 + 4*B*omega^2*x*y*cosfai0*costheta*sinfai0*sintheta - 2*pi*B*omega*v*y*sinalpha*costheta*sintheta - 4*B*fai0*omega*v*y*sinalpha*costheta*sintheta + 4*B*omega*v*y*cosfai0*sinalpha*costheta*sinfai0*sintheta))/2];
    end
elseif vn == 0 && omega ~= 0
    switch type
        case 3
            
            FM = [-y*pi*(sintheta + mu*costheta)*(2*A + B*omega^2*x^2*costheta^2 + B*omega^2*y^2*sintheta^2 + 2*B*v^2*cosalpha^2*sintheta^2 + B*v^2*sinalpha^2*costheta^2 + 2*B*omega*v*x*sinalpha*costheta^2 - 2*B*omega^2*x*y*costheta*sintheta - 2*B*omega*v*y*sinalpha*costheta*sintheta);
                    -2*B*v*y*pi*cosalpha*sintheta*(costheta - mu*sintheta)*(omega*x*costheta - omega*y*sintheta + v*sinalpha*costheta);
                    2*B*v*y*pi*cosalpha*sintheta*(omega*x*costheta - omega*y*sintheta + v*sinalpha*costheta)*(y*sintheta - x*costheta + mu*y*costheta + mu*x*sintheta)
                    -y*pi*(costheta - mu*sintheta)*(2*A + B*omega^2*x^2*costheta^2 + B*omega^2*y^2*sintheta^2 + 2*B*v^2*cosalpha^2*sintheta^2 + B*v^2*sinalpha^2*costheta^2 + 2*B*omega*v*x*sinalpha*costheta^2 - 2*B*omega^2*x*y*costheta*sintheta - 2*B*omega*v*y*sinalpha*costheta*sintheta)];
        case 1

            FM = [ -(y*(sintheta + mu*costheta)*(4*A*fai0 + 2*pi*A - B*v^2*sin2fai0*sinalpha^2*costheta^2 + 2*pi*B*v^2*cosalpha^2*sintheta^2 + pi*B*v^2*sinalpha^2*costheta^2 + 4*B*fai0*v^2*cosalpha^2*sintheta^2 + 2*B*fai0*v^2*sinalpha^2*costheta^2 - B*omega^2*x^2*sin2fai0*costheta^2 - B*omega^2*y^2*sin2fai0*sintheta^2 + pi*B*omega^2*x^2*costheta^2 + pi*B*omega^2*y^2*sintheta^2 + 2*B*fai0*omega^2*x^2*costheta^2 + 2*B*fai0*omega^2*y^2*sintheta^2 - 2*B*fai0*omega^2*x*y*sin(2*theta) - B*omega^2*x*y*pi*sin(2*theta) - 2*B*omega*v*x*sin2fai0*sinalpha*costheta^2 + 2*B*omega^2*x*y*sin2fai0*costheta*sintheta + 2*pi*B*omega*v*x*sinalpha*costheta^2 + 4*B*fai0*omega*v*x*sinalpha*costheta^2 - 8*B*v^2*cosalpha*cosfai0*sinalpha*costheta*sintheta + 8*B*omega*v*y*cosalpha*cosfai0*sintheta^2 - 8*B*omega*v*x*cosalpha*cosfai0*costheta*sintheta + 2*B*omega*v*y*sin2fai0*sinalpha*costheta*sintheta - 2*pi*B*omega*v*y*sinalpha*costheta*sintheta - 4*B*fai0*omega*v*y*sinalpha*costheta*sintheta))/2;
                (y*(costheta - mu*sintheta)*(6*A*cosfai0 - 2*B*v^2*cosfai0^3*sinalpha^2*costheta^2 + 6*B*omega^2*x^2*cosfai0*costheta^2 + 6*B*omega^2*y^2*cosfai0*sintheta^2 - 2*B*omega^2*x^2*cosfai0^3*costheta^2 + 6*B*v^2*cosfai0*sinalpha^2*costheta^2 + 6*B*v^2*cosalpha^2*cosfai0*sintheta^2 - 2*B*omega^2*y^2*cosfai0^3*sintheta^2 + 3*B*v^2*sin2fai0*cosalpha*sinalpha*costheta*sintheta - 3*pi*B*v^2*cosalpha*sinalpha*costheta*sintheta - 4*B*omega*v*x*cosfai0^3*sinalpha*costheta^2 - 6*B*fai0*v^2*cosalpha*sinalpha*costheta*sintheta - 3*B*omega*v*y*sin2fai0*cosalpha*sintheta^2 + 4*B*omega^2*x*y*cosfai0^3*costheta*sintheta + 3*pi*B*omega*v*y*cosalpha*sintheta^2 + 6*B*fai0*omega*v*y*cosalpha*sintheta^2 + 12*B*omega*v*x*cosfai0*sinalpha*costheta^2 - 12*B*omega^2*x*y*cosfai0*costheta*sintheta - 12*B*omega*v*y*cosfai0*sinalpha*costheta*sintheta + 3*B*omega*v*x*sin2fai0*cosalpha*costheta*sintheta + 4*B*omega*v*y*cosfai0^3*sinalpha*costheta*sintheta - 3*pi*B*omega*v*x*cosalpha*costheta*sintheta - 6*B*fai0*omega*v*x*cosalpha*costheta*sintheta))/3;
                -(y*(y*sintheta - x*costheta + mu*y*costheta + mu*x*sintheta)*(6*A*cosfai0 - 2*B*v^2*cosfai0^3*sinalpha^2*costheta^2 + 6*B*omega^2*x^2*cosfai0*costheta^2 + 6*B*omega^2*y^2*cosfai0*sintheta^2 - 2*B*omega^2*x^2*cosfai0^3*costheta^2 + 6*B*v^2*cosfai0*sinalpha^2*costheta^2 + 6*B*v^2*cosalpha^2*cosfai0*sintheta^2 - 2*B*omega^2*y^2*cosfai0^3*sintheta^2 + 3*B*v^2*sin2fai0*cosalpha*sinalpha*costheta*sintheta - 3*pi*B*v^2*cosalpha*sinalpha*costheta*sintheta - 4*B*omega*v*x*cosfai0^3*sinalpha*costheta^2 - 6*B*fai0*v^2*cosalpha*sinalpha*costheta*sintheta - 3*B*omega*v*y*sin2fai0*cosalpha*sintheta^2 + 4*B*omega^2*x*y*cosfai0^3*costheta*sintheta + 3*pi*B*omega*v*y*cosalpha*sintheta^2 + 6*B*fai0*omega*v*y*cosalpha*sintheta^2 + 12*B*omega*v*x*cosfai0*sinalpha*costheta^2 - 12*B*omega^2*x*y*cosfai0*costheta*sintheta - 12*B*omega*v*y*cosfai0*sinalpha*costheta*sintheta + 3*B*omega*v*x*sin2fai0*cosalpha*costheta*sintheta + 4*B*omega*v*y*cosfai0^3*sinalpha*costheta*sintheta - 3*pi*B*omega*v*x*cosalpha*costheta*sintheta - 6*B*fai0*omega*v*x*cosalpha*costheta*sintheta))/3
                -(y*(costheta - mu*sintheta)*(4*A*fai0 + 2*pi*A + 2*pi*B*v^2*cosalpha^2*sintheta^2 + pi*B*v^2*sinalpha^2*costheta^2 + 4*B*fai0*v^2*cosalpha^2*sintheta^2 + 2*B*fai0*v^2*sinalpha^2*costheta^2 + pi*B*omega^2*x^2*costheta^2 + pi*B*omega^2*y^2*sintheta^2 + 2*B*fai0*omega^2*x^2*costheta^2 + 2*B*fai0*omega^2*y^2*sintheta^2 - 2*B*fai0*omega^2*x*y*sin(2*theta) - 2*B*omega^2*x^2*cosfai0*costheta^2*sinfai0 - 2*B*omega^2*y^2*cosfai0*sinfai0*sintheta^2 - 2*B*v^2*cosfai0*sinalpha^2*costheta^2*sinfai0 - B*omega^2*x*y*pi*sin(2*theta) + 2*pi*B*omega*v*x*sinalpha*costheta^2 + 4*B*fai0*omega*v*x*sinalpha*costheta^2 - 8*B*v^2*cosalpha*cosfai0*sinalpha*costheta*sintheta + 8*B*omega*v*y*cosalpha*cosfai0*sintheta^2 - 8*B*omega*v*x*cosalpha*cosfai0*costheta*sintheta - 4*B*omega*v*x*cosfai0*sinalpha*costheta^2*sinfai0 + 4*B*omega^2*x*y*cosfai0*costheta*sinfai0*sintheta - 2*pi*B*omega*v*y*sinalpha*costheta*sintheta - 4*B*fai0*omega*v*y*sinalpha*costheta*sintheta + 4*B*omega*v*y*cosfai0*sinalpha*costheta*sinfai0*sintheta))/2];
        case 2

            FM = [-(y*(sintheta + mu*costheta)*(4*A*fai0 + 2*pi*A - B*v^2*sin2fai0*sinalpha^2*costheta^2 + 2*pi*B*v^2*cosalpha^2*sintheta^2 + pi*B*v^2*sinalpha^2*costheta^2 + 4*B*fai0*v^2*cosalpha^2*sintheta^2 + 2*B*fai0*v^2*sinalpha^2*costheta^2 - B*omega^2*x^2*sin2fai0*costheta^2 - B*omega^2*y^2*sin2fai0*sintheta^2 + pi*B*omega^2*x^2*costheta^2 + pi*B*omega^2*y^2*sintheta^2 + 2*B*fai0*omega^2*x^2*costheta^2 + 2*B*fai0*omega^2*y^2*sintheta^2 - 2*B*fai0*omega^2*x*y*sin(2*theta) - B*omega^2*x*y*pi*sin(2*theta) - 2*B*omega*v*x*sin2fai0*sinalpha*costheta^2 + 2*B*omega^2*x*y*sin2fai0*costheta*sintheta + 2*pi*B*omega*v*x*sinalpha*costheta^2 + 4*B*fai0*omega*v*x*sinalpha*costheta^2 + 8*B*v^2*cosalpha*cosfai0*sinalpha*costheta*sintheta - 8*B*omega*v*y*cosalpha*cosfai0*sintheta^2 + 8*B*omega*v*x*cosalpha*cosfai0*costheta*sintheta + 2*B*omega*v*y*sin2fai0*sinalpha*costheta*sintheta - 2*pi*B*omega*v*y*sinalpha*costheta*sintheta - 4*B*fai0*omega*v*y*sinalpha*costheta*sintheta))/2;
                -(y*(costheta - mu*sintheta)*(6*A*cosfai0 - 2*B*v^2*cosfai0^3*sinalpha^2*costheta^2 + 6*B*omega^2*x^2*cosfai0*costheta^2 + 6*B*omega^2*y^2*cosfai0*sintheta^2 - 2*B*omega^2*x^2*cosfai0^3*costheta^2 + 6*B*v^2*cosfai0*sinalpha^2*costheta^2 + 6*B*v^2*cosalpha^2*cosfai0*sintheta^2 - 2*B*omega^2*y^2*cosfai0^3*sintheta^2 - 3*B*v^2*sin2fai0*cosalpha*sinalpha*costheta*sintheta + 3*pi*B*v^2*cosalpha*sinalpha*costheta*sintheta - 4*B*omega*v*x*cosfai0^3*sinalpha*costheta^2 + 6*B*fai0*v^2*cosalpha*sinalpha*costheta*sintheta + 3*B*omega*v*y*sin2fai0*cosalpha*sintheta^2 + 4*B*omega^2*x*y*cosfai0^3*costheta*sintheta - 3*pi*B*omega*v*y*cosalpha*sintheta^2 - 6*B*fai0*omega*v*y*cosalpha*sintheta^2 + 12*B*omega*v*x*cosfai0*sinalpha*costheta^2 - 12*B*omega^2*x*y*cosfai0*costheta*sintheta - 12*B*omega*v*y*cosfai0*sinalpha*costheta*sintheta - 3*B*omega*v*x*sin2fai0*cosalpha*costheta*sintheta + 4*B*omega*v*y*cosfai0^3*sinalpha*costheta*sintheta + 3*pi*B*omega*v*x*cosalpha*costheta*sintheta + 6*B*fai0*omega*v*x*cosalpha*costheta*sintheta))/3;
                (y*(y*sintheta - x*costheta + mu*y*costheta + mu*x*sintheta)*(6*A*cosfai0 - 2*B*v^2*cosfai0^3*sinalpha^2*costheta^2 + 6*B*omega^2*x^2*cosfai0*costheta^2 + 6*B*omega^2*y^2*cosfai0*sintheta^2 - 2*B*omega^2*x^2*cosfai0^3*costheta^2 + 6*B*v^2*cosfai0*sinalpha^2*costheta^2 + 6*B*v^2*cosalpha^2*cosfai0*sintheta^2 - 2*B*omega^2*y^2*cosfai0^3*sintheta^2 - 3*B*v^2*sin2fai0*cosalpha*sinalpha*costheta*sintheta + 3*pi*B*v^2*cosalpha*sinalpha*costheta*sintheta - 4*B*omega*v*x*cosfai0^3*sinalpha*costheta^2 + 6*B*fai0*v^2*cosalpha*sinalpha*costheta*sintheta + 3*B*omega*v*y*sin2fai0*cosalpha*sintheta^2 + 4*B*omega^2*x*y*cosfai0^3*costheta*sintheta - 3*pi*B*omega*v*y*cosalpha*sintheta^2 - 6*B*fai0*omega*v*y*cosalpha*sintheta^2 + 12*B*omega*v*x*cosfai0*sinalpha*costheta^2 - 12*B*omega^2*x*y*cosfai0*costheta*sintheta - 12*B*omega*v*y*cosfai0*sinalpha*costheta*sintheta - 3*B*omega*v*x*sin2fai0*cosalpha*costheta*sintheta + 4*B*omega*v*y*cosfai0^3*sinalpha*costheta*sintheta + 3*pi*B*omega*v*x*cosalpha*costheta*sintheta + 6*B*fai0*omega*v*x*cosalpha*costheta*sintheta))/3
                -(y*(costheta - mu*sintheta)*(4*A*fai0 + 2*pi*A + 2*pi*B*v^2*cosalpha^2*sintheta^2 + pi*B*v^2*sinalpha^2*costheta^2 + 4*B*fai0*v^2*cosalpha^2*sintheta^2 + 2*B*fai0*v^2*sinalpha^2*costheta^2 + pi*B*omega^2*x^2*costheta^2 + pi*B*omega^2*y^2*sintheta^2 + 2*B*fai0*omega^2*x^2*costheta^2 + 2*B*fai0*omega^2*y^2*sintheta^2 - 2*B*fai0*omega^2*x*y*sin(2*theta) - 2*B*omega^2*x^2*cosfai0*costheta^2*sinfai0 - 2*B*omega^2*y^2*cosfai0*sinfai0*sintheta^2 - 2*B*v^2*cosfai0*sinalpha^2*costheta^2*sinfai0 - B*omega^2*x*y*pi*sin(2*theta) + 2*pi*B*omega*v*x*sinalpha*costheta^2 + 4*B*fai0*omega*v*x*sinalpha*costheta^2 + 8*B*v^2*cosalpha*cosfai0*sinalpha*costheta*sintheta - 8*B*omega*v*y*cosalpha*cosfai0*sintheta^2 + 8*B*omega*v*x*cosalpha*cosfai0*costheta*sintheta - 4*B*omega*v*x*cosfai0*sinalpha*costheta^2*sinfai0 + 4*B*omega^2*x*y*cosfai0*costheta*sinfai0*sintheta - 2*pi*B*omega*v*y*sinalpha*costheta*sintheta - 4*B*fai0*omega*v*y*sinalpha*costheta*sintheta + 4*B*omega*v*y*cosfai0*sinalpha*costheta*sinfai0*sintheta))/2];
    end
elseif vn ~= 0 && omega == 0
    switch type
        case 3
            
            FM = [-y*pi*(sintheta + mu*costheta)*(2*A + 2*B*vn^2 + 2*B*v^2*cosalpha^2*sintheta^2 + B*v^2*sinalpha^2*costheta^2 + 4*B*v*vn*cosalpha*sintheta);
                 -2*B*v*y*pi*sinalpha*costheta*(vn + v*cosalpha*sintheta)*(costheta - mu*sintheta);
                 2*B*v*y*pi*sinalpha*costheta*(vn + v*cosalpha*sintheta)*(y*sintheta - x*costheta + mu*y*costheta + mu*x*sintheta)
                 -y*pi*(costheta - mu*sintheta)*(2*A + 2*B*vn^2 + 2*B*v^2*cosalpha^2*sintheta^2 + B*v^2*sinalpha^2*costheta^2 + 4*B*v*vn*cosalpha*sintheta)];
        case 1
            
            FM = [-(y*(sintheta + mu*costheta)*(4*A*fai0 + 2*pi*A + 2*pi*B*vn^2 + 4*B*fai0*vn^2 - B*v^2*sin2fai0*sinalpha^2*costheta^2 + 2*pi*B*v^2*cosalpha^2*sintheta^2 + pi*B*v^2*sinalpha^2*costheta^2 + 4*B*fai0*v^2*cosalpha^2*sintheta^2 + 2*B*fai0*v^2*sinalpha^2*costheta^2 - 8*B*v*vn*cosfai0*sinalpha*costheta + 4*pi*B*v*vn*cosalpha*sintheta + 8*B*fai0*v*vn*cosalpha*sintheta - 8*B*v^2*cosalpha*cosfai0*sinalpha*costheta*sintheta))/2;
                 (y*(costheta - mu*sintheta)*(6*A*cosfai0 + 6*B*vn^2*cosfai0 - 2*B*v^2*cosfai0^3*sinalpha^2*costheta^2 + 6*B*v^2*cosfai0*sinalpha^2*costheta^2 + 6*B*v^2*cosalpha^2*cosfai0*sintheta^2 + 12*B*v*vn*cosalpha*cosfai0*sintheta + 3*B*v*vn*sin2fai0*sinalpha*costheta - 3*pi*B*v*vn*sinalpha*costheta - 6*B*fai0*v*vn*sinalpha*costheta + 3*B*v^2*sin2fai0*cosalpha*sinalpha*costheta*sintheta - 3*pi*B*v^2*cosalpha*sinalpha*costheta*sintheta - 6*B*fai0*v^2*cosalpha*sinalpha*costheta*sintheta))/3;
                 -(y*(y*sintheta - x*costheta + mu*y*costheta + mu*x*sintheta)*(6*A*cosfai0 + 6*B*vn^2*cosfai0 - 2*B*v^2*cosfai0^3*sinalpha^2*costheta^2 + 6*B*v^2*cosfai0*sinalpha^2*costheta^2 + 6*B*v^2*cosalpha^2*cosfai0*sintheta^2 + 12*B*v*vn*cosalpha*cosfai0*sintheta + 3*B*v*vn*sin2fai0*sinalpha*costheta - 3*pi*B*v*vn*sinalpha*costheta - 6*B*fai0*v*vn*sinalpha*costheta + 3*B*v^2*sin2fai0*cosalpha*sinalpha*costheta*sintheta - 3*pi*B*v^2*cosalpha*sinalpha*costheta*sintheta - 6*B*fai0*v^2*cosalpha*sinalpha*costheta*sintheta))/3
                 -(y*(costheta - mu*sintheta)*(4*A*fai0 + 2*pi*A + 2*pi*B*vn^2 + 4*B*fai0*vn^2 + 2*pi*B*v^2*cosalpha^2*sintheta^2 + pi*B*v^2*sinalpha^2*costheta^2 + 4*B*fai0*v^2*cosalpha^2*sintheta^2 + 2*B*fai0*v^2*sinalpha^2*costheta^2 - 8*B*v*vn*cosfai0*sinalpha*costheta - 2*B*v^2*cosfai0*sinalpha^2*costheta^2*sinfai0 + 4*pi*B*v*vn*cosalpha*sintheta + 8*B*fai0*v*vn*cosalpha*sintheta - 8*B*v^2*cosalpha*cosfai0*sinalpha*costheta*sintheta))/2];
        case 2
            
            FM = [-(y*(sintheta + mu*costheta)*(4*A*fai0 + 2*pi*A + 2*pi*B*vn^2 + 4*B*fai0*vn^2 - B*v^2*sin2fai0*sinalpha^2*costheta^2 + 2*pi*B*v^2*cosalpha^2*sintheta^2 + pi*B*v^2*sinalpha^2*costheta^2 + 4*B*fai0*v^2*cosalpha^2*sintheta^2 + 2*B*fai0*v^2*sinalpha^2*costheta^2 + 8*B*v*vn*cosfai0*sinalpha*costheta + 4*pi*B*v*vn*cosalpha*sintheta + 8*B*fai0*v*vn*cosalpha*sintheta + 8*B*v^2*cosalpha*cosfai0*sinalpha*costheta*sintheta))/2;
                -(y*(costheta - mu*sintheta)*(6*A*cosfai0 + 6*B*vn^2*cosfai0 - 2*B*v^2*cosfai0^3*sinalpha^2*costheta^2 + 6*B*v^2*cosfai0*sinalpha^2*costheta^2 + 6*B*v^2*cosalpha^2*cosfai0*sintheta^2 + 12*B*v*vn*cosalpha*cosfai0*sintheta - 3*B*v*vn*sin2fai0*sinalpha*costheta + 3*pi*B*v*vn*sinalpha*costheta + 6*B*fai0*v*vn*sinalpha*costheta - 3*B*v^2*sin2fai0*cosalpha*sinalpha*costheta*sintheta + 3*pi*B*v^2*cosalpha*sinalpha*costheta*sintheta + 6*B*fai0*v^2*cosalpha*sinalpha*costheta*sintheta))/3;
                (y*(y*sintheta - x*costheta + mu*y*costheta + mu*x*sintheta)*(6*A*cosfai0 + 6*B*vn^2*cosfai0 - 2*B*v^2*cosfai0^3*sinalpha^2*costheta^2 + 6*B*v^2*cosfai0*sinalpha^2*costheta^2 + 6*B*v^2*cosalpha^2*cosfai0*sintheta^2 + 12*B*v*vn*cosalpha*cosfai0*sintheta - 3*B*v*vn*sin2fai0*sinalpha*costheta + 3*pi*B*v*vn*sinalpha*costheta + 6*B*fai0*v*vn*sinalpha*costheta - 3*B*v^2*sin2fai0*cosalpha*sinalpha*costheta*sintheta + 3*pi*B*v^2*cosalpha*sinalpha*costheta*sintheta + 6*B*fai0*v^2*cosalpha*sinalpha*costheta*sintheta))/3
                -(y*(costheta - mu*sintheta)*(4*A*fai0 + 2*pi*A + 2*pi*B*vn^2 + 4*B*fai0*vn^2 + 2*pi*B*v^2*cosalpha^2*sintheta^2 + pi*B*v^2*sinalpha^2*costheta^2 + 4*B*fai0*v^2*cosalpha^2*sintheta^2 + 2*B*fai0*v^2*sinalpha^2*costheta^2 + 8*B*v*vn*cosfai0*sinalpha*costheta - 2*B*v^2*cosfai0*sinalpha^2*costheta^2*sinfai0 + 4*pi*B*v*vn*cosalpha*sintheta + 8*B*fai0*v*vn*cosalpha*sintheta + 8*B*v^2*cosalpha*cosfai0*sinalpha*costheta*sintheta))/2];
    end
else
    switch type
        case 3
            
            FM = [-y*pi*(sintheta + mu*costheta)*(2*A + B*v^2*sinalpha^2 + 2*B*v^2*sintheta^2 - 3*B*v^2*sinalpha^2*sintheta^2);
                 -2*B*v^2*y*pi*cosalpha*sinalpha*costheta*sintheta*(costheta - mu*sintheta);
                 2*B*v^2*y*pi*cosalpha*sinalpha*costheta*sintheta*(y*sintheta - x*costheta + mu*y*costheta + mu*x*sintheta)
                 -y*pi*(costheta - mu*sintheta)*(2*A + B*v^2*sinalpha^2 + 2*B*v^2*sintheta^2 - 3*B*v^2*sinalpha^2*sintheta^2)];
        case 1
            
            FM = [-(y*(sintheta + mu*costheta)*(4*A*fai0 + 2*pi*A - B*v^2*sin2fai0*sinalpha^2*costheta^2 + 2*pi*B*v^2*cosalpha^2*sintheta^2 + pi*B*v^2*sinalpha^2*costheta^2 + 4*B*fai0*v^2*cosalpha^2*sintheta^2 + 2*B*fai0*v^2*sinalpha^2*costheta^2 - 8*B*v^2*cosalpha*cosfai0*sinalpha*costheta*sintheta))/2;
                (y*(costheta - mu*sintheta)*(6*A*cosfai0 - 2*B*v^2*cosfai0^3*sinalpha^2*costheta^2 + 6*B*v^2*cosfai0*sinalpha^2*costheta^2 + 6*B*v^2*cosalpha^2*cosfai0*sintheta^2 + 3*B*v^2*sin2fai0*cosalpha*sinalpha*costheta*sintheta - 3*pi*B*v^2*cosalpha*sinalpha*costheta*sintheta - 6*B*fai0*v^2*cosalpha*sinalpha*costheta*sintheta))/3;
                -(y*(y*sintheta - x*costheta + mu*y*costheta + mu*x*sintheta)*(6*A*cosfai0 - 2*B*v^2*cosfai0^3*sinalpha^2*costheta^2 + 6*B*v^2*cosfai0*sinalpha^2*costheta^2 + 6*B*v^2*cosalpha^2*cosfai0*sintheta^2 + 3*B*v^2*sin2fai0*cosalpha*sinalpha*costheta*sintheta - 3*pi*B*v^2*cosalpha*sinalpha*costheta*sintheta - 6*B*fai0*v^2*cosalpha*sinalpha*costheta*sintheta))/3
                -(y*(costheta - mu*sintheta)*(4*A*fai0 + 2*pi*A + 2*pi*B*v^2*cosalpha^2*sintheta^2 + pi*B*v^2*sinalpha^2*costheta^2 + 4*B*fai0*v^2*cosalpha^2*sintheta^2 + 2*B*fai0*v^2*sinalpha^2*costheta^2 - 2*B*v^2*cosfai0*sinalpha^2*costheta^2*sinfai0 - 8*B*v^2*cosalpha*cosfai0*sinalpha*costheta*sintheta))/2];
        case 2
            
            FM = [-(y*(sintheta + mu*costheta)*(4*A*fai0 + 2*pi*A - B*v^2*sin2fai0*sinalpha^2*costheta^2 + 2*pi*B*v^2*cosalpha^2*sintheta^2 + pi*B*v^2*sinalpha^2*costheta^2 + 4*B*fai0*v^2*cosalpha^2*sintheta^2 + 2*B*fai0*v^2*sinalpha^2*costheta^2 + 8*B*v^2*cosalpha*cosfai0*sinalpha*costheta*sintheta))/2;
                 -(y*(costheta - mu*sintheta)*(6*A*cosfai0 - 2*B*v^2*cosfai0^3*sinalpha^2*costheta^2 + 6*B*v^2*cosfai0*sinalpha^2*costheta^2 + 6*B*v^2*cosalpha^2*cosfai0*sintheta^2 - 3*B*v^2*sin2fai0*cosalpha*sinalpha*costheta*sintheta + 3*pi*B*v^2*cosalpha*sinalpha*costheta*sintheta + 6*B*fai0*v^2*cosalpha*sinalpha*costheta*sintheta))/3;
                 (y*(y*sintheta - x*costheta + mu*y*costheta + mu*x*sintheta)*(6*A*cosfai0 - 2*B*v^2*cosfai0^3*sinalpha^2*costheta^2 + 6*B*v^2*cosfai0*sinalpha^2*costheta^2 + 6*B*v^2*cosalpha^2*cosfai0*sintheta^2 - 3*B*v^2*sin2fai0*cosalpha*sinalpha*costheta*sintheta + 3*pi*B*v^2*cosalpha*sinalpha*costheta*sintheta + 6*B*fai0*v^2*cosalpha*sinalpha*costheta*sintheta))/3
                 -(y*(costheta - mu*sintheta)*(4*A*fai0 + 2*pi*A + 2*pi*B*v^2*cosalpha^2*sintheta^2 + pi*B*v^2*sinalpha^2*costheta^2 + 4*B*fai0*v^2*cosalpha^2*sintheta^2 + 2*B*fai0*v^2*sinalpha^2*costheta^2 - 2*B*v^2*cosfai0*sinalpha^2*costheta^2*sinfai0 + 8*B*v^2*cosalpha*cosfai0*sinalpha*costheta*sintheta))/2];
    end
end
